In [1]:
import pandas as pd
import numpy as np

In [4]:
target = pd.read_csv('../baseline2.csv').drop(columns=['Unnamed: 0'])

In [5]:
target['stock_id'] = target['stock_id'].astype('category')
target.head()

,stock_id,time_id,sigma,target,size,spread,time_diff,log_time_diff,timefunc
0,0,5,0.004499,0.004136,3179,7.922559,15,2.708050,0.310975
1,0,11,0.001204,0.001445,1287,4.118409,23,3.135494,0.723982
2,0,16,0.002369,0.002168,2161,6.476585,35,3.555348,0.971598
3,0,31,0.002574,0.002195,1962,7.627233,28,3.332205,0.849035
4,0,62,0.001894,0.001747,1791,4.302926,25,3.218876,0.779443

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

def rmsre(y_true, y_pred):
    return np.mean(((y_true - y_pred) / y_true)**2)**0.5

def print_stats(x, y, model):
    y_pred = model.predict(x)
    error = rmsre(y, y_pred)
    r2 = r2_score(y, y_pred)
    print(error)
    print(r2)
X = target.drop(columns=['time_id', 'log_time_diff', 'target'])
y = target['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

       stock_id     sigma    size    spread  time_diff  timefunc
58414        16  0.001897    1534  5.126072         16  0.357830
43172        11  0.003754   11508  4.499456         10  0.146488
374773      110  0.004756    5644  6.320810          2  1.126273
185674       53  0.003054    8712  2.864278          5  0.646393
365303      108  0.007700  165055  4.297629          3  0.611016

58414     0.001544
43172     0.003463
374773    0.003391
185674    0.002863
365303    0.004143
Name: target, dtype: float64

In [8]:
import xgboost as xgb

model_xgb = xgb.XGBRegressor(n_estimators=3000, max_depth=3, enable_categorical=True)
model_xgb.fit(X_train, y_train)
print_stats(X_test, y_test, model_xgb)

print_stats(X_train, y_train, model_xgb)

0.29148831924361857
0.7944008818429649
0.28728481268911044
0.8181439280713362

In [9]:
print(model_xgb.feature_importances_)

X_train.columns

[0.02265396 0.9360577  0.00881488 0.00994696 0.01325198 0.00927454]

Index(['stock_id', 'sigma', 'size', 'spread', 'time_diff', 'timefunc'], dtype='object')

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
X_train.head()

       stock_id     sigma   size     spread  time_diff  timefunc
330253       98  0.022680   4289  43.201393         12  0.328561
284195       84  0.003405   9093   3.125977          2  0.830183
218505       64  0.004135  57094   2.208139          3  0.790423
163819       46  0.002165  46587   2.159519          4  0.486106
366439      108  0.000996  32855   2.126939          3  0.611016

In [19]:
#Here I need you, I need to run a different Linear Regression for each stock_id.

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
error = rmsre(y_test, y_pred)
print(error)
r2 = r2_score(y_test, y_pred)
print(r2)

0.3664259901912755
0.762842567656838